-- AgriEnergyConnect Database Schema & Seed Script

-- Drop tables if exist (for clean setup)
IF OBJECT_ID('dbo.Products', 'U') IS NOT NULL DROP TABLE dbo.Products;
IF OBJECT_ID('dbo.Farmers', 'U') IS NOT NULL DROP TABLE dbo.Farmers;
IF OBJECT_ID('dbo.AspNetUserRoles', 'U') IS NOT NULL DROP TABLE dbo.AspNetUserRoles;
IF OBJECT_ID('dbo.AspNetRoles', 'U') IS NOT NULL DROP TABLE dbo.AspNetRoles;
IF OBJECT_ID('dbo.AspNetUsers', 'U') IS NOT NULL DROP TABLE dbo.AspNetUsers;

-- Identity tables
CREATE TABLE AspNetUsers (
    Id NVARCHAR(450) NOT NULL PRIMARY KEY,
    UserName NVARCHAR(256),
    NormalizedUserName NVARCHAR(256),
    Email NVARCHAR(256),
    NormalizedEmail NVARCHAR(256),
    EmailConfirmed BIT NOT NULL,
    PasswordHash NVARCHAR(MAX),
    SecurityStamp NVARCHAR(MAX),
    ConcurrencyStamp NVARCHAR(MAX),
    PhoneNumber NVARCHAR(MAX),
    PhoneNumberConfirmed BIT NOT NULL,
    TwoFactorEnabled BIT NOT NULL,
    LockoutEnd DATETIMEOFFSET,
    LockoutEnabled BIT NOT NULL,
    AccessFailedCount INT NOT NULL
);

CREATE TABLE AspNetRoles (
    Id NVARCHAR(450) NOT NULL PRIMARY KEY,
    Name NVARCHAR(256),
    NormalizedName NVARCHAR(256),
    ConcurrencyStamp NVARCHAR(MAX)
);

CREATE TABLE AspNetUserRoles (
    UserId NVARCHAR(450) NOT NULL,
    RoleId NVARCHAR(450) NOT NULL,
    PRIMARY KEY (UserId, RoleId),
    CONSTRAINT FK_UserRoles_Users FOREIGN KEY(UserId) REFERENCES AspNetUsers(Id) ON DELETE CASCADE,
    CONSTRAINT FK_UserRoles_Roles FOREIGN KEY(RoleId) REFERENCES AspNetRoles(Id) ON DELETE CASCADE
);

-- Domain tables
CREATE TABLE Farmers (
    Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    Name NVARCHAR(120) NOT NULL,
    Email NVARCHAR(256),
    IdentityUserId NVARCHAR(450),
    CONSTRAINT FK_Farmers_User FOREIGN KEY(IdentityUserId) REFERENCES AspNetUsers(Id)
);

CREATE TABLE Products (
    Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    Name NVARCHAR(120) NOT NULL,
    Category NVARCHAR(80) NOT NULL,
    ProductionDate DATETIME2 NOT NULL,
    FarmerId INT NOT NULL,
    CONSTRAINT FK_Products_Farmers FOREIGN KEY(FarmerId) REFERENCES Farmers(Id) ON DELETE CASCADE
);

-- Seed Roles
INSERT INTO AspNetRoles (Id, Name, NormalizedName, ConcurrencyStamp)
VALUES 
  ('role-emp', 'Employee', 'EMPLOYEE', NEWID()),
  ('role-far', 'Farmer', 'FARMER', NEWID());

-- Seed Users (password hashes are placeholders, should be generated by Identity in real seed)
INSERT INTO AspNetUsers (Id, UserName, NormalizedUserName, Email, NormalizedEmail, EmailConfirmed, PasswordHash, SecurityStamp, ConcurrencyStamp, PhoneNumberConfirmed, TwoFactorEnabled, LockoutEnabled, AccessFailedCount)
VALUES 
  ('user-emp', 'employee@agri.com', 'EMPLOYEE@AGRI.COM', 'employee@agri.com', 'EMPLOYEE@AGRI.COM', 1, 'HASHEDPASSWORD', NEWID(), NEWID(), 0, 0, 1, 0),
  ('user-far', 'farmer@agri.com', 'FARMER@AGRI.COM', 'farmer@agri.com', 'FARMER@AGRI.COM', 1, 'HASHEDPASSWORD', NEWID(), NEWID(), 0, 0, 1, 0);

-- Assign roles
INSERT INTO AspNetUserRoles (UserId, RoleId) VALUES ('user-emp','role-emp');
INSERT INTO AspNetUserRoles (UserId, RoleId) VALUES ('user-far','role-far');

-- Seed Farmer profile
INSERT INTO Farmers (Name, Email, IdentityUserId)
VALUES ('Sample Farmer', 'farmer@agri.com', 'user-far');

-- Seed Products
INSERT INTO Products (Name, Category, ProductionDate, FarmerId)
VALUES
('Tomatoes','Vegetable', DATEADD(DAY,-10, GETUTCDATE()), 1),
('Corn','Grain', DATEADD(DAY,-30, GETUTCDATE()), 1),
('Basil','Herb', DATEADD(DAY,-5, GETUTCDATE()), 1);
